//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderEntry
    {
        public int Id { get; set; }
        public int Amount { get; set; }
        public int OrderId { get; set; }
        public int Product_Id { get; set; }
    
        public virtual Order OrderSet { get; set; }
        public virtual Product ProductSet { get; set; }
    }
}
